refactor "space" symbol to "whitespace"
yoav-lavi/melody pull request #34
Opened 2022-02-22 14:26 UTC by amirali

Hi!  
In the Regex, `\s` will match any whitespace, not just the space bar. So I think its symbol name is better to be `whitespace` instead of `space`. 
And I'm sorry if it sounds like a dumb PR.

2022-02-22 14:29 UTC, yoav-lavi requested changes
A few minor tweaks

2022-02-22 14:29 UTC, yoav-lavi commented on crates/melody_compiler/src/lib.rs
> +    WhiteSpaceSymbol,
```suggestion
    WhitespaceSymbol,
```

2022-02-22 14:29 UTC, yoav-lavi commented on crates/melody_compiler/src/lib.rs
> +            Token::WhiteSpaceSymbol => handle_quantifier(String::from("\\s"), quantifier.clone(), false),
```suggestion
            Token::WhitespaceSymbol => handle_quantifier(String::from("\\s"), quantifier.clone(), false),
```

2022-02-22 14:29 UTC, yoav-lavi commented on docs/docs/status.md
> +| `<whitespace>;`                          | `\s`                  | ✅          |
```suggestion
| `<whitespace>;`                     | `\s`                  | ✅          |
```

2022-02-22 14:29 UTC, yoav-lavi commented on docs/docs/status.md
> +| `not <whitespace>;`                      | `\S`                  | ❌          |
```suggestion
| `not <whitespace>;`                 | `\S`                  | ❌          |
```

2022-02-22 14:29 UTC, yoav-lavi commented
Not at all, there's actually an open issue for this!

https://github.com/yoav-lavi/melody/issues/32

2022-02-22 14:30 UTC, yoav-lavi commented
We'd also need to change the examples in the readme / docs to fit this (possibly using " ")

2022-02-22 14:31 UTC, yoav-lavi commented
Thank you for your contribution!

2022-02-22 16:02 UTC, amirali commented on crates/melody_compiler/src/lib.rs
> +    WhiteSpaceSymbol,
931ec457da9fc50a4f9ea185f67c30ece403f7ba

2022-02-22 16:02 UTC, amirali commented on crates/melody_compiler/src/lib.rs
> +            Token::WhiteSpaceSymbol => handle_quantifier(String::from("\\s"), quantifier.clone(), false),
931ec457da9fc50a4f9ea185f67c30ece403f7ba

2022-02-22 16:02 UTC, amirali commented on docs/docs/status.md
> +| `not <whitespace>;`                      | `\S`                  | ❌          |
384e946e43a1eff0fee1ad5dc52750fce36ea093

2022-02-22 16:04 UTC, amirali commented
And I also added the `<alphabet>` symbol (9dd17ae771093122540201081a04ebed05be3153) and `<space>` symbol (69a9439d5a2aa4728aac7d55e4a9d3a37a2b37f3)

2022-02-24 17:49 UTC, yoav-lavi commented
Hey @amirali, could you please update this PR to the current state of the repo? Thank you!

2022-02-25 00:06 UTC, amirali commented
Sorry I didn't notice it has conflict with main branch

2022-02-25 15:49 UTC, yoav-lavi commented
No worries! That happened after the PR

2022-02-26 13:52 UTC, yoav-lavi approved these changes
Thank you for your contribution!

2022-02-26 13:52 UTC, merged